FROM node:22

RUN npm install eslint typescript @angular/cli -g
WORKDIR /async-modal-ngx

ENV LANG C.UTF-8
ENV TZ America/Sao_Paulo

EXPOSE 9229
EXPOSE 4200

# The run the start script
CMD [ "/bin/bash" ]
